vocabulary = {
    "your":     0,
    "cat":      1,
    "is":       2,
    "a":        3,
    "lovely":   4,
    "my":       5,
    "you":      6,
    "olle":     7,
    "matrea":   8,
    "dad":         9,
    "mom":         10,
    "pet":         11,
    "rosie":         12,
    "fumble":        13,
    "petrol":         14,
    "tummy":         15,
    "sage":         16,
    "duck":         17,
    "liver":         18,
    "onion":         19,
    "tomato":         20,
    "pepper":         21,
    "langchain":         22,
    "are":         23,
    "the":         24,
    "best":         25,
    "of":         26,
    "all":         27,
    "bum":         28,
    "lol":         29,
    "cool":         30,
    "story":         31,
    "man":         32,
    "woman":         33,
    "[UNK]":    34  # Unknown token for words not in the vocabulary
}